import type {
  DrugProduct,
  ProductType,
  ProductCategory,
  DEASchedule,
  RouteOfAdministration,
  ActiveIngredient,
  DrugInteraction,
} from '@/types';

export interface SeedProduct extends DrugProduct {
  dataSource: 'SEED';
  apiCountry: string;
  fgCountry: string;
}

const now = '2026-02-27T00:00:00.000Z';

function makeProduct(
  overrides: Partial<SeedProduct> & {
    id: string;
    ndc: string;
    name: string;
    brandName: string;
    genericName: string;
    manufacturer: string;
    category: ProductCategory;
    activeIngredients: ActiveIngredient[];
    apiCountry: string;
    fgCountry: string;
  },
): SeedProduct {
  return {
    labelerName: overrides.manufacturer.split(' ')[0],
    productType: 'prescription' as ProductType,
    schedule: 'unscheduled' as DEASchedule,
    routeOfAdministration: 'oral' as RouteOfAdministration,
    dosageForm: 'Tablet',
    strength: '10',
    strengthUnit: 'mg',
    packageSize: '30',
    packageType: 'Bottle',
    description: `${overrides.brandName} (${overrides.genericName}) - ${overrides.category} medication`,
    inactiveIngredients: ['Microcrystalline Cellulose', 'Magnesium Stearate', 'Lactose Monohydrate'],
    indications: ['See prescribing information'],
    contraindications: ['Known hypersensitivity to active ingredient'],
    warnings: ['Keep out of reach of children'],
    sideEffects: ['Nausea', 'Headache'],
    interactions: [],
    storageConditions: 'Store at 20-25°C (68-77°F)',
    requiresPrescription: true,
    isControlled: false,
    isAvailable: true,
    price: 25.99,
    currency: 'USD',
    fdaApprovalDate: '2020-01-15',
    expirationDate: '2027-12-31',
    lotNumber: 'SEED-001',
    barcode: '300000000001',
    createdAt: now,
    updatedAt: now,
    dataSource: 'SEED',
    ...overrides,
  };
}

/**
 * Generate 32 deterministic seed drug products spanning multiple
 * therapeutic classes, manufacturers, and risk levels.
 */
export function generateSeedProducts(): SeedProduct[] {
  return [
    // === US-Made Products (High MIA) ===
    makeProduct({
      id: 'seed-001',
      ndc: '0002-4462-30',
      name: 'Lisinopril 10mg',
      brandName: 'Prinivil',
      genericName: 'Lisinopril',
      manufacturer: 'Merck & Co., USA',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Lisinopril', strength: '10', unit: 'mg' }],
      strength: '10',
      strengthUnit: 'mg',
      price: 12.50,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-001',
      barcode: '300024462301',
    }),
    makeProduct({
      id: 'seed-002',
      ndc: '0006-0749-31',
      name: 'Metformin 500mg',
      brandName: 'Glucophage',
      genericName: 'Metformin Hydrochloride',
      manufacturer: 'Bristol-Myers Squibb, USA',
      category: 'endocrine',
      activeIngredients: [{ name: 'Metformin Hydrochloride', strength: '500', unit: 'mg' }],
      strength: '500',
      strengthUnit: 'mg',
      price: 8.99,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-002',
      barcode: '300067493101',
    }),
    makeProduct({
      id: 'seed-003',
      ndc: '0093-0058-01',
      name: 'Amoxicillin 500mg',
      brandName: 'Amoxil',
      genericName: 'Amoxicillin Trihydrate',
      manufacturer: 'Teva Pharmaceuticals USA',
      category: 'antibiotic',
      activeIngredients: [{ name: 'Amoxicillin Trihydrate', strength: '500', unit: 'mg' }],
      strength: '500',
      strengthUnit: 'mg',
      dosageForm: 'Capsule',
      price: 9.75,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-003',
      barcode: '300930058011',
    }),
    makeProduct({
      id: 'seed-004',
      ndc: '0074-3799-13',
      name: 'Atorvastatin 20mg',
      brandName: 'Lipitor',
      genericName: 'Atorvastatin Calcium',
      manufacturer: 'Pfizer Inc., USA',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Atorvastatin Calcium', strength: '20', unit: 'mg' }],
      strength: '20',
      strengthUnit: 'mg',
      price: 15.30,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-004',
      barcode: '300743799131',
    }),
    makeProduct({
      id: 'seed-005',
      ndc: '0049-0050-66',
      name: 'Sertraline 50mg',
      brandName: 'Zoloft',
      genericName: 'Sertraline Hydrochloride',
      manufacturer: 'Pfizer Inc., USA',
      category: 'psychiatric',
      activeIngredients: [{ name: 'Sertraline Hydrochloride', strength: '50', unit: 'mg' }],
      strength: '50',
      strengthUnit: 'mg',
      price: 14.20,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-005',
      barcode: '300490050661',
    }),
    makeProduct({
      id: 'seed-006',
      ndc: '0173-0519-00',
      name: 'Albuterol Inhaler',
      brandName: 'Ventolin HFA',
      genericName: 'Albuterol Sulfate',
      manufacturer: 'GlaxoSmithKline, USA',
      category: 'respiratory',
      activeIngredients: [{ name: 'Albuterol Sulfate', strength: '90', unit: 'mcg/actuation' }],
      strength: '90',
      strengthUnit: 'mcg',
      routeOfAdministration: 'inhalation',
      dosageForm: 'Metered Dose Inhaler',
      price: 35.00,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-006',
      barcode: '301730519001',
    }),
    makeProduct({
      id: 'seed-007',
      ndc: '0002-3228-30',
      name: 'Omeprazole 20mg',
      brandName: 'Prilosec',
      genericName: 'Omeprazole',
      manufacturer: 'AstraZeneca, USA',
      category: 'gastrointestinal',
      activeIngredients: [{ name: 'Omeprazole', strength: '20', unit: 'mg' }],
      strength: '20',
      strengthUnit: 'mg',
      dosageForm: 'Delayed-Release Capsule',
      productType: 'otc',
      requiresPrescription: false,
      price: 18.50,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-007',
      barcode: '300023228301',
    }),
    makeProduct({
      id: 'seed-008',
      ndc: '0555-0972-02',
      name: 'Levothyroxine 50mcg',
      brandName: 'Synthroid',
      genericName: 'Levothyroxine Sodium',
      manufacturer: 'AbbVie Inc., USA',
      category: 'endocrine',
      activeIngredients: [{ name: 'Levothyroxine Sodium', strength: '50', unit: 'mcg' }],
      strength: '50',
      strengthUnit: 'mcg',
      price: 22.00,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-008',
      barcode: '305550972021',
    }),
    makeProduct({
      id: 'seed-009',
      ndc: '0378-1805-01',
      name: 'Amlodipine 5mg',
      brandName: 'Norvasc',
      genericName: 'Amlodipine Besylate',
      manufacturer: 'Mylan Pharmaceuticals, USA',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Amlodipine Besylate', strength: '5', unit: 'mg' }],
      strength: '5',
      strengthUnit: 'mg',
      price: 11.00,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-009',
      barcode: '303781805011',
    }),
    makeProduct({
      id: 'seed-010',
      ndc: '0591-0405-01',
      name: 'Hydrocodone/APAP 5/325mg',
      brandName: 'Vicodin',
      genericName: 'Hydrocodone Bitartrate / Acetaminophen',
      manufacturer: 'Watson Laboratories, USA',
      category: 'analgesic',
      schedule: 'II' as DEASchedule,
      isControlled: true,
      activeIngredients: [
        { name: 'Hydrocodone Bitartrate', strength: '5', unit: 'mg' },
        { name: 'Acetaminophen', strength: '325', unit: 'mg' },
      ],
      strength: '5/325',
      strengthUnit: 'mg',
      interactions: [
        { drugName: 'Alcohol', severity: 'major', description: 'Increased CNS depression' } as DrugInteraction,
        { drugName: 'Benzodiazepines', severity: 'contraindicated', description: 'Risk of fatal respiratory depression' } as DrugInteraction,
      ],
      warnings: ['Risk of addiction and abuse', 'Risk of respiratory depression', 'Hepatotoxicity risk with acetaminophen'],
      price: 28.50,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-010',
      barcode: '305910405011',
    }),

    // === Puerto Rico Products (High MIA - PR) ===
    makeProduct({
      id: 'seed-011',
      ndc: '0069-3150-66',
      name: 'Gabapentin 300mg',
      brandName: 'Neurontin',
      genericName: 'Gabapentin',
      manufacturer: 'Pfizer Puerto Rico Inc.',
      category: 'neurological',
      activeIngredients: [{ name: 'Gabapentin', strength: '300', unit: 'mg' }],
      strength: '300',
      strengthUnit: 'mg',
      dosageForm: 'Capsule',
      price: 16.80,
      apiCountry: 'Puerto Rico',
      fgCountry: 'Puerto Rico',
      lotNumber: 'SEED-011',
      barcode: '300693150661',
    }),
    makeProduct({
      id: 'seed-012',
      ndc: '0069-4200-30',
      name: 'Losartan 50mg',
      brandName: 'Cozaar',
      genericName: 'Losartan Potassium',
      manufacturer: 'Merck Sharp & Dohme, Puerto Rico',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Losartan Potassium', strength: '50', unit: 'mg' }],
      strength: '50',
      strengthUnit: 'mg',
      price: 13.40,
      apiCountry: 'Puerto Rico',
      fgCountry: 'Puerto Rico',
      lotNumber: 'SEED-012',
      barcode: '300694200301',
    }),
    makeProduct({
      id: 'seed-013',
      ndc: '0069-5500-30',
      name: 'Montelukast 10mg',
      brandName: 'Singulair',
      genericName: 'Montelukast Sodium',
      manufacturer: 'Organon Puerto Rico',
      category: 'respiratory',
      activeIngredients: [{ name: 'Montelukast Sodium', strength: '10', unit: 'mg' }],
      strength: '10',
      strengthUnit: 'mg',
      price: 19.99,
      apiCountry: 'US',
      fgCountry: 'Puerto Rico',
      lotNumber: 'SEED-013',
      barcode: '300695500301',
    }),

    // === India-Sourced Products (Medium MIA - TAA) ===
    makeProduct({
      id: 'seed-014',
      ndc: '65862-0176-30',
      name: 'Metoprolol Succinate 25mg ER',
      brandName: 'Toprol-XL Generic',
      genericName: 'Metoprolol Succinate',
      manufacturer: 'Aurobindo Pharma, India',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Metoprolol Succinate', strength: '25', unit: 'mg' }],
      strength: '25',
      strengthUnit: 'mg',
      dosageForm: 'Extended-Release Tablet',
      price: 7.50,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-014',
      barcode: '365862017630',
    }),
    makeProduct({
      id: 'seed-015',
      ndc: '65862-0202-90',
      name: 'Clopidogrel 75mg',
      brandName: 'Plavix Generic',
      genericName: 'Clopidogrel Bisulfate',
      manufacturer: 'Aurobindo Pharma, India',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Clopidogrel Bisulfate', strength: '75', unit: 'mg' }],
      strength: '75',
      strengthUnit: 'mg',
      price: 10.25,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-015',
      barcode: '365862020290',
    }),
    makeProduct({
      id: 'seed-016',
      ndc: '68382-0025-01',
      name: 'Ciprofloxacin 500mg',
      brandName: 'Cipro Generic',
      genericName: 'Ciprofloxacin Hydrochloride',
      manufacturer: 'Zydus Lifesciences, India',
      category: 'antibiotic',
      activeIngredients: [{ name: 'Ciprofloxacin Hydrochloride', strength: '500', unit: 'mg' }],
      strength: '500',
      strengthUnit: 'mg',
      interactions: [
        { drugName: 'Warfarin', severity: 'major', description: 'Increased anticoagulant effect' } as DrugInteraction,
      ],
      warnings: ['Tendon rupture risk', 'Peripheral neuropathy risk'],
      price: 11.75,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-016',
      barcode: '368382002501',
    }),
    makeProduct({
      id: 'seed-017',
      ndc: '69097-0183-07',
      name: 'Escitalopram 10mg',
      brandName: 'Lexapro Generic',
      genericName: 'Escitalopram Oxalate',
      manufacturer: 'Cipla Ltd., Mumbai, India',
      category: 'psychiatric',
      activeIngredients: [{ name: 'Escitalopram Oxalate', strength: '10', unit: 'mg' }],
      strength: '10',
      strengthUnit: 'mg',
      price: 9.80,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-017',
      barcode: '369097018307',
    }),
    makeProduct({
      id: 'seed-018',
      ndc: '16714-0295-01',
      name: 'Pantoprazole 40mg',
      brandName: 'Protonix Generic',
      genericName: 'Pantoprazole Sodium',
      manufacturer: 'Dr. Reddys Laboratories, Hyderabad, India',
      category: 'gastrointestinal',
      activeIngredients: [{ name: 'Pantoprazole Sodium', strength: '40', unit: 'mg' }],
      strength: '40',
      strengthUnit: 'mg',
      dosageForm: 'Delayed-Release Tablet',
      price: 14.50,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-018',
      barcode: '316714029501',
    }),
    makeProduct({
      id: 'seed-019',
      ndc: '16714-0400-01',
      name: 'Rosuvastatin 10mg',
      brandName: 'Crestor Generic',
      genericName: 'Rosuvastatin Calcium',
      manufacturer: 'Dr. Reddys Laboratories, India',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Rosuvastatin Calcium', strength: '10', unit: 'mg' }],
      strength: '10',
      strengthUnit: 'mg',
      price: 11.99,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-019',
      barcode: '316714040001',
    }),
    makeProduct({
      id: 'seed-020',
      ndc: '65862-0500-90',
      name: 'Duloxetine 30mg',
      brandName: 'Cymbalta Generic',
      genericName: 'Duloxetine Hydrochloride',
      manufacturer: 'Lupin Pharmaceuticals, India',
      category: 'psychiatric',
      activeIngredients: [{ name: 'Duloxetine Hydrochloride', strength: '30', unit: 'mg' }],
      strength: '30',
      strengthUnit: 'mg',
      dosageForm: 'Delayed-Release Capsule',
      price: 18.25,
      apiCountry: 'India',
      fgCountry: 'India',
      lotNumber: 'SEED-020',
      barcode: '365862050090',
    }),

    // === China-Sourced Products (Low MIA) ===
    makeProduct({
      id: 'seed-021',
      ndc: '70010-0491-30',
      name: 'Ibuprofen 200mg',
      brandName: 'Advil Generic',
      genericName: 'Ibuprofen',
      manufacturer: 'Hubei Biocause Pharmaceutical, China',
      category: 'analgesic',
      activeIngredients: [{ name: 'Ibuprofen', strength: '200', unit: 'mg' }],
      strength: '200',
      strengthUnit: 'mg',
      productType: 'otc',
      requiresPrescription: false,
      price: 4.99,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-021',
      barcode: '370010049130',
    }),
    makeProduct({
      id: 'seed-022',
      ndc: '70010-0505-60',
      name: 'Acetaminophen 500mg',
      brandName: 'Tylenol Generic',
      genericName: 'Acetaminophen',
      manufacturer: 'Zhejiang Kangle Pharmaceutical, China',
      category: 'analgesic',
      activeIngredients: [{ name: 'Acetaminophen', strength: '500', unit: 'mg' }],
      strength: '500',
      strengthUnit: 'mg',
      productType: 'otc',
      requiresPrescription: false,
      interactions: [
        { drugName: 'Warfarin', severity: 'moderate', description: 'May increase INR' } as DrugInteraction,
      ],
      warnings: ['Hepatotoxicity risk at high doses', 'Do not exceed 3000mg/day'],
      price: 3.99,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-022',
      barcode: '370010050560',
    }),
    makeProduct({
      id: 'seed-023',
      ndc: '70010-0620-30',
      name: 'Metformin HCl 850mg',
      brandName: 'Metformin Generic CN',
      genericName: 'Metformin Hydrochloride',
      manufacturer: 'Shanghai Pharmaceuticals, Shanghai, China',
      category: 'endocrine',
      activeIngredients: [{ name: 'Metformin Hydrochloride', strength: '850', unit: 'mg' }],
      strength: '850',
      strengthUnit: 'mg',
      price: 5.25,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-023',
      barcode: '370010062030',
    }),
    makeProduct({
      id: 'seed-024',
      ndc: '70010-0733-90',
      name: 'Azithromycin 250mg',
      brandName: 'Zithromax Generic CN',
      genericName: 'Azithromycin Dihydrate',
      manufacturer: 'CSPC Pharmaceutical, China',
      category: 'antibiotic',
      activeIngredients: [{ name: 'Azithromycin Dihydrate', strength: '250', unit: 'mg' }],
      strength: '250',
      strengthUnit: 'mg',
      packageSize: '6',
      packageType: 'Z-Pack',
      price: 6.50,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-024',
      barcode: '370010073390',
    }),
    makeProduct({
      id: 'seed-025',
      ndc: '70010-0845-30',
      name: 'Losartan 25mg',
      brandName: 'Cozaar Generic CN',
      genericName: 'Losartan Potassium',
      manufacturer: 'Zhejiang Huahai Pharmaceutical, China',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Losartan Potassium', strength: '25', unit: 'mg' }],
      strength: '25',
      strengthUnit: 'mg',
      warnings: ['Keep out of reach of children', 'Potential NDMA impurity concern'],
      price: 4.50,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-025',
      barcode: '370010084530',
    }),
    makeProduct({
      id: 'seed-026',
      ndc: '70010-0901-60',
      name: 'Vitamin D3 2000IU',
      brandName: 'Cholecalciferol',
      genericName: 'Cholecalciferol (Vitamin D3)',
      manufacturer: 'Xiamen Kingdomway, China',
      category: 'other',
      activeIngredients: [{ name: 'Cholecalciferol', strength: '2000', unit: 'IU' }],
      strength: '2000',
      strengthUnit: 'IU',
      productType: 'supplement',
      requiresPrescription: false,
      dosageForm: 'Softgel',
      price: 7.99,
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-026',
      barcode: '370010090160',
    }),

    // === Mixed Origin Products (API from one country, FG from another) ===
    makeProduct({
      id: 'seed-027',
      ndc: '0781-5180-31',
      name: 'Prednisone 10mg',
      brandName: 'Deltasone Generic',
      genericName: 'Prednisone',
      manufacturer: 'Sandoz Inc., USA (API: India)',
      category: 'immunological',
      activeIngredients: [{ name: 'Prednisone', strength: '10', unit: 'mg' }],
      strength: '10',
      strengthUnit: 'mg',
      price: 6.75,
      apiCountry: 'India',
      fgCountry: 'US',
      lotNumber: 'SEED-027',
      barcode: '307815180311',
    }),
    makeProduct({
      id: 'seed-028',
      ndc: '0378-6105-01',
      name: 'Tamsulosin 0.4mg',
      brandName: 'Flomax Generic',
      genericName: 'Tamsulosin Hydrochloride',
      manufacturer: 'Mylan Pharmaceuticals, USA (API: China)',
      category: 'musculoskeletal',
      activeIngredients: [{ name: 'Tamsulosin Hydrochloride', strength: '0.4', unit: 'mg' }],
      strength: '0.4',
      strengthUnit: 'mg',
      dosageForm: 'Capsule',
      price: 15.80,
      apiCountry: 'China',
      fgCountry: 'US',
      lotNumber: 'SEED-028',
      barcode: '303786105011',
    }),
    makeProduct({
      id: 'seed-029',
      ndc: '43547-0351-03',
      name: 'Meloxicam 15mg',
      brandName: 'Mobic Generic',
      genericName: 'Meloxicam',
      manufacturer: 'Solco Healthcare, USA (API: India)',
      category: 'musculoskeletal',
      activeIngredients: [{ name: 'Meloxicam', strength: '15', unit: 'mg' }],
      strength: '15',
      strengthUnit: 'mg',
      price: 8.25,
      apiCountry: 'India',
      fgCountry: 'US',
      lotNumber: 'SEED-029',
      barcode: '343547035103',
    }),

    // === TAA Country Products (Israel, Ireland, Germany, Japan, Canada) ===
    makeProduct({
      id: 'seed-030',
      ndc: '0093-7180-56',
      name: 'Amlodipine/Valsartan 5/160mg',
      brandName: 'Exforge Generic',
      genericName: 'Amlodipine / Valsartan',
      manufacturer: 'Teva Pharmaceutical, Israel',
      category: 'cardiovascular',
      activeIngredients: [
        { name: 'Amlodipine Besylate', strength: '5', unit: 'mg' },
        { name: 'Valsartan', strength: '160', unit: 'mg' },
      ],
      strength: '5/160',
      strengthUnit: 'mg',
      price: 22.50,
      apiCountry: 'Israel',
      fgCountry: 'Israel',
      lotNumber: 'SEED-030',
      barcode: '300937180561',
    }),
    makeProduct({
      id: 'seed-031',
      ndc: '0078-0401-15',
      name: 'Fluticasone Propionate 50mcg Nasal',
      brandName: 'Flonase Generic',
      genericName: 'Fluticasone Propionate',
      manufacturer: 'Perrigo Ireland',
      category: 'respiratory',
      activeIngredients: [{ name: 'Fluticasone Propionate', strength: '50', unit: 'mcg/spray' }],
      strength: '50',
      strengthUnit: 'mcg',
      routeOfAdministration: 'nasal',
      dosageForm: 'Nasal Spray',
      productType: 'otc',
      requiresPrescription: false,
      price: 16.99,
      apiCountry: 'Ireland',
      fgCountry: 'Ireland',
      lotNumber: 'SEED-031',
      barcode: '300780401151',
    }),
    makeProduct({
      id: 'seed-032',
      ndc: '0024-5852-31',
      name: 'Insulin Glargine 100U/mL',
      brandName: 'Lantus',
      genericName: 'Insulin Glargine',
      manufacturer: 'Sanofi-Aventis Deutschland GmbH, Germany',
      category: 'endocrine',
      activeIngredients: [{ name: 'Insulin Glargine', strength: '100', unit: 'units/mL' }],
      strength: '100',
      strengthUnit: 'units/mL',
      routeOfAdministration: 'subcutaneous',
      dosageForm: 'Solution for Injection',
      storageConditions: 'Refrigerate at 2-8°C (36-46°F). Do not freeze.',
      price: 285.00,
      apiCountry: 'Germany',
      fgCountry: 'Germany',
      lotNumber: 'SEED-032',
      barcode: '300245852311',
    }),
    makeProduct({
      id: 'seed-033',
      ndc: '0186-0372-01',
      name: 'Candesartan 16mg',
      brandName: 'Atacand',
      genericName: 'Candesartan Cilexetil',
      manufacturer: 'AstraZeneca KK, Japan',
      category: 'cardiovascular',
      activeIngredients: [{ name: 'Candesartan Cilexetil', strength: '16', unit: 'mg' }],
      strength: '16',
      strengthUnit: 'mg',
      price: 42.00,
      apiCountry: 'Japan',
      fgCountry: 'Japan',
      lotNumber: 'SEED-033',
      barcode: '301860372011',
    }),
    makeProduct({
      id: 'seed-034',
      ndc: '0024-1100-10',
      name: 'Ketoconazole 2% Cream',
      brandName: 'Nizoral',
      genericName: 'Ketoconazole',
      manufacturer: 'Janssen Pharmaceutica, Canada',
      category: 'antifungal',
      activeIngredients: [{ name: 'Ketoconazole', strength: '2', unit: '%' }],
      strength: '2',
      strengthUnit: '%',
      routeOfAdministration: 'topical',
      dosageForm: 'Cream',
      packageSize: '30',
      packageType: 'Tube',
      price: 24.50,
      apiCountry: 'Canada',
      fgCountry: 'Canada',
      lotNumber: 'SEED-034',
      barcode: '300241100101',
    }),

    // === Special cases: unavailable, controlled, ophthalmic ===
    makeProduct({
      id: 'seed-035',
      ndc: '0023-6150-10',
      name: 'Timolol 0.5% Ophthalmic',
      brandName: 'Timoptic',
      genericName: 'Timolol Maleate',
      manufacturer: 'Bausch & Lomb, USA',
      category: 'ophthalmic',
      activeIngredients: [{ name: 'Timolol Maleate', strength: '0.5', unit: '%' }],
      strength: '0.5',
      strengthUnit: '%',
      routeOfAdministration: 'ophthalmic',
      dosageForm: 'Ophthalmic Solution',
      packageSize: '5',
      packageType: 'Drop Bottle',
      price: 32.00,
      apiCountry: 'US',
      fgCountry: 'US',
      lotNumber: 'SEED-035',
      barcode: '300236150101',
    }),
    makeProduct({
      id: 'seed-036',
      ndc: '70010-9999-01',
      name: 'Doxycycline 100mg',
      brandName: 'Doryx Generic CN',
      genericName: 'Doxycycline Hyclate',
      manufacturer: 'Northeast Pharmaceutical, Beijing, China',
      category: 'antibiotic',
      activeIngredients: [{ name: 'Doxycycline Hyclate', strength: '100', unit: 'mg' }],
      strength: '100',
      strengthUnit: 'mg',
      dosageForm: 'Capsule',
      isAvailable: false,
      price: 8.50,
      warnings: ['Photosensitivity risk', 'Not for children under 8', 'Keep out of reach of children'],
      apiCountry: 'China',
      fgCountry: 'China',
      lotNumber: 'SEED-036',
      barcode: '370010999901',
    }),
  ];
}
