import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import BriefingPreview from '../BriefingPreview';
import type { BriefingData } from '../BriefingPreview';

const mockBriefing: BriefingData = {
  title: 'Insulin Supply Chain Analysis',
  date: 'February 28, 2026',
  audience: 'Congressional',
  sections: [
    {
      heading: 'Executive Summary',
      content:
        'This briefing examines the **insulin supply chain** and identifies key risk areas for Congressional review.',
    },
    {
      heading: 'Key Findings',
      content:
        '- **Pricing volatility** has increased 15% year-over-year\n- Three major manufacturers control 90% of supply\n- TAA compliance gaps identified in two product lines',
    },
    {
      heading: 'Risk Assessment',
      content:
        '- **Supply Chain Risk**: High — single-source dependencies\n- **Regulatory Risk**: Moderate — pending FDA guidance',
    },
    {
      heading: 'Recommendations',
      content:
        '- Diversify procurement sources to reduce single-supplier risk\n- Implement enhanced monitoring for price fluctuations',
    },
  ],
  sources: [
    'FDA National Drug Code Directory (NDCDIR)',
    'Federal Supply Schedule (FSS) Pricing Data',
    'CMS Drug Pricing Reports',
  ],
};

describe('BriefingPreview', () => {
  it('renders the briefing title', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(screen.getByText('Insulin Supply Chain Analysis')).toBeInTheDocument();
  });

  it('renders the iRemedy AI branding header', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(screen.getByText('iRemedy AI Intelligence Briefing')).toBeInTheDocument();
  });

  it('renders date and audience metadata', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(screen.getByText(/February 28, 2026/)).toBeInTheDocument();
    expect(screen.getByText(/Audience: Congressional/)).toBeInTheDocument();
  });

  it('renders all section headings', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(screen.getByText('Executive Summary')).toBeInTheDocument();
    expect(screen.getByText('Key Findings')).toBeInTheDocument();
    expect(screen.getByText('Risk Assessment')).toBeInTheDocument();
    expect(screen.getByText('Recommendations')).toBeInTheDocument();
  });

  it('renders markdown-style content with bold text', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    // Bold text should be rendered as <strong>
    const boldElements = document.querySelectorAll('strong');
    const boldTexts = Array.from(boldElements).map((el) => el.textContent);
    expect(boldTexts).toContain('insulin supply chain');
    expect(boldTexts).toContain('Pricing volatility');
  });

  it('renders bullet point items as list elements', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    const listItems = document.querySelectorAll('li');
    expect(listItems.length).toBeGreaterThan(0);
    // Check specific bullet items
    expect(screen.getByText(/Three major manufacturers/)).toBeInTheDocument();
  });

  it('renders sources section with numbered citations', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(screen.getByText('Sources')).toBeInTheDocument();
    expect(
      screen.getByText('FDA National Drug Code Directory (NDCDIR)'),
    ).toBeInTheDocument();
    expect(
      screen.getByText('Federal Supply Schedule (FSS) Pricing Data'),
    ).toBeInTheDocument();
    expect(screen.getByText('CMS Drug Pricing Reports')).toBeInTheDocument();
  });

  it('renders footer with confidentiality notice', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    expect(
      screen.getByText(/Generated by iRemedy AI/),
    ).toBeInTheDocument();
  });

  it('print button triggers window.print()', () => {
    const printSpy = vi.spyOn(window, 'print').mockImplementation(() => {});
    render(<BriefingPreview briefing={mockBriefing} />);

    const printButton = screen.getByRole('button', { name: /print/i });
    fireEvent.click(printButton);

    expect(printSpy).toHaveBeenCalledOnce();
    printSpy.mockRestore();
  });

  it('renders gradient dividers as separators', () => {
    render(<BriefingPreview briefing={mockBriefing} />);
    const separators = document.querySelectorAll('[role="separator"]');
    expect(separators.length).toBeGreaterThan(0);
  });

  it('handles briefing with no sources gracefully', () => {
    const noSourcesBriefing: BriefingData = {
      ...mockBriefing,
      sources: [],
    };
    render(<BriefingPreview briefing={noSourcesBriefing} />);
    // Sources heading should not appear
    expect(screen.queryByText('Sources')).not.toBeInTheDocument();
  });
});
