import { useRef } from 'react';
import { PatrioticButton, GradientDivider } from '@/components/design-system';

export interface BriefingSection {
  heading: string;
  content: string;
}

export interface BriefingData {
  title: string;
  date: string;
  audience: string;
  sections: BriefingSection[];
  sources: string[];
}

interface BriefingPreviewProps {
  briefing: BriefingData;
}

function renderTextWithBold(text: string): React.ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i}>{part.slice(2, -2)}</strong>;
    }
    return <span key={i}>{part}</span>;
  });
}

function renderContent(content: string) {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let listItems: string[] = [];

  const flushList = () => {
    if (listItems.length > 0) {
      elements.push(
        <ul key={`list-${elements.length}`} className="ml-5 list-disc space-y-1.5">
          {listItems.map((item, i) => (
            <li key={i} className="text-navy/80">
              {renderTextWithBold(item)}
            </li>
          ))}
        </ul>,
      );
      listItems = [];
    }
  };

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      listItems.push(trimmed.slice(2));
    } else {
      flushList();
      if (trimmed.length > 0) {
        elements.push(
          <p key={`p-${elements.length}`} className="text-navy/80 leading-relaxed">
            {renderTextWithBold(trimmed)}
          </p>,
        );
      }
    }
  }
  flushList();

  return elements;
}

const BriefingPreview = ({ briefing }: BriefingPreviewProps) => {
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-end gap-3 print:hidden">
        <PatrioticButton size="sm" onClick={handlePrint}>
          Print / Export
        </PatrioticButton>
      </div>

      <div
        ref={printRef}
        className="rounded-xl border border-navy/10 bg-white p-8 shadow-sm print:border-none print:shadow-none"
      >
        {/* Header with branding */}
        <div className="mb-6 text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-gold">
            iRemedy AI Intelligence Briefing
          </p>
          <h2 className="mt-2 font-heading text-2xl font-bold text-navy">
            {briefing.title}
          </h2>
          <p className="mt-1 text-sm text-navy/50">
            {briefing.date} &middot; Audience: {briefing.audience}
          </p>
        </div>

        <GradientDivider className="my-6" />

        {/* Briefing sections */}
        <div className="space-y-6">
          {briefing.sections.map((section, idx) => (
            <section key={idx}>
              <h3 className="mb-2 font-heading text-lg font-semibold text-navy">
                {section.heading}
              </h3>
              <div className="space-y-2">{renderContent(section.content)}</div>
              {idx < briefing.sections.length - 1 && (
                <GradientDivider className="mt-6 opacity-30" />
              )}
            </section>
          ))}
        </div>

        {/* Sources */}
        {briefing.sources.length > 0 && (
          <>
            <GradientDivider className="my-6" />
            <section>
              <h3 className="mb-2 font-heading text-lg font-semibold text-navy">
                Sources
              </h3>
              <ol className="ml-5 list-decimal space-y-1">
                {briefing.sources.map((source, idx) => (
                  <li key={idx} className="text-sm text-navy/70">
                    {source}
                  </li>
                ))}
              </ol>
            </section>
          </>
        )}

        {/* Footer */}
        <div className="mt-8 border-t border-navy/10 pt-4 text-center text-xs text-navy/40">
          Generated by iRemedy AI &middot; Confidential Intelligence Document
        </div>
      </div>
    </div>
  );
};

export default BriefingPreview;
